# Generated by Django 5.2 on 2025-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('date_membership', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Our_team_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='اسم گروه ما')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('contact_us_text', models.TextField(blank=True, null=True, verbose_name='متن تماس با ما')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='ادرس')),
                ('city_us', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('phone_us', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email_us', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ادرس ایمیل')),
                ('whatsapp_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک واتساپ')),
                ('instagram_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک اینساگرام')),
                ('telegram_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
